bills/urls.py
from django.urls import path
from . import views

app_name = 'bills'
urlpatterns = [
	path('', views.index, name='index'),
	path('<str:state>/<int:session>/<str:name>', views.detail, name='detail'),
	path('<str:state>/<int:session>/<str:name>/vote/', views.vote, name='vote'),
]

represent/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import TemplateView

urlpatterns = [
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('bills/', include('bills.urls')),
    path('legislators/', include('legislators.urls')),
    path('constituents/', include('constituents.urls')),
    path('constituents/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls)
]

bills/models.py
from django.db import models

from constituents.models import Vote


class Bill(models.Model):
    bill_id = models.CharField(max_length=45, primary_key=True)
    state = models.CharField(max_length=9, choices=[('Tennessee', 'Tennessee')])
    session = models.IntegerField()
    chamber = models.CharField(max_length=5, choices=[('upper', 'Senate'), ('lower', 'House')])
    name = models.CharField(max_length=7)
    title = models.TextField()
    scraped_subjects = models.CharField(max_length=200, null=True)
    subjects = models.ManyToManyField('Subject')
    topics = models.ManyToManyField('Topic')
    sponsors = models.ManyToManyField('legislators.Legislator')
    companion_name = models.CharField(max_length=7)

    def get_actions(self):
        a = Action.objects.filter(
            state=self.state,
            session=self.session,
            name=self.name
        ).order_by('date')

        return a

    def count_votes(self, position):
        c = Vote.objects.filter(
            state=self.state,
            session=self.session,
            name=self.name,
            position=position
        ).count()

        return c


class Action(models.Model):
    bill_id = models.ForeignKey('Bill', on_delete=models.CASCADE)
    state = models.CharField(max_length=9, choices=[('Tennessee', 'Tennessee')])
    session = models.IntegerField()
    name = models.CharField(max_length=7)
    action = models.CharField(max_length=256)
    actor = models.CharField(
        max_length=53,
        choices=[
            ('ocd-organization/47760e16-8071-49dd-bd9f-354198c8b653', 'Senate'),
            ('ocd-organization/d4c442c8-d4d7-4ea9-a3fd-b856b2904d8b', 'House')
        ]
    )
    classification = models.CharField(max_length=32)
    date = models.DateTimeField()


class Subject(models.Model):
    subject = models.CharField(max_length=100)


class Topic(models.Model):
    topic = models.CharField(max_length=100)

bills/forms.py
from django import forms

from constituents.models import Vote


class VoteForm(forms.ModelForm):

	class Meta:
		model = Vote
		fields = ('position',)

bills/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse

from .forms import VoteForm
from .models import Bill, Subject
from constituents.models import Vote


@login_required
def index(request):

	constituent_id = request.user.constituent_id
	votes = Vote.objects.filter(
		Q(name__contains='HB') | Q(companion_name='nan'),
		constituent_id=constituent_id
	)

	# subjects = Constituent.objects.get(constituent_id=constituent_id).subjects
	subjects = [i.id for i in Subject.objects.filter(subject__in=['Education'])]
	interest = Bill.objects.filter(
		Q(name__contains='HB') | Q(companion_name='nan'),
		subjects__in=subjects,
		session=111,
	)

	# Don't suggest bills constituent has already voted on
	for v in votes:
		interest = interest \
			.exclude(state=v.state, session=v.session, name=v.name) \
			.exclude(state=v.state, session=v.session, companion_name=v.name)

	context = {
		'support': votes.filter(position='support'),
		'oppose': votes.filter(position='oppose'),
		'interest': interest[:10]
	}

	return render(request, 'bills/index.html', context)


@login_required
def detail(request, state, session, name):
	b = get_object_or_404(Bill, state=state, session=session, name=name)

	try:
		p = Vote.objects.get(
			state=state,
			session=session,
			name=name,
			constituent=request.user.constituent_id
		).position
	except Vote.DoesNotExist:
		p = None

	if p in ['support', 'oppose']:
		position = f'You {p} this bill.'
	elif p == 'indifferent':
		position = 'You are indifferent toward this bill.'
	else:
		position = 'You have not expressed a position on this bill.'

	actions = b.get_actions()

	context = {
		'bill': b,
		'position': position,
		'support': b.count_votes(position='support'),
		'house_actions': actions.filter(actor='lower'),
		'senate_actions': actions.filter(actor='upper')
	}

	return render(request, 'bills/detail.html', context=context)


@login_required
def vote(request, state, session, name):
	constituent_id = request.user.constituent_id
	bill_id = Bill.objects.get(state=state, session=session, name=name)

	# Find companion bill (SB to HB) which may or may not exist
	try:
		companion_name = Bill.objects.get(
			state=state,
			session=session,
			name=name
		).companion_name
	except Bill.DoesNotExist:
		companion_name = None

	# Register vote for bill
	try:
		v = Vote.objects.get(
			state=state,
			session=session,
			name=name,
			constituent_id=constituent_id
		)
	except Vote.DoesNotExist:
		if request.method == 'POST':
			f = VoteForm(request.POST)
			if f.is_valid():
				v = f.save(commit=False)
				v.constituent_id = constituent_id
				v.bill_id = bill_id
				v.state = state
				v.session = session
				v.name = name
				v.companion_name = companion_name
				v.save()
	else:
		v.position = request.POST['position']
		v.save()

	# Register vote for companion bill if exists
	if companion_name is not None:
		try:
			c = Vote.objects.get(
				state=state,
				session=session,
				name=companion_name,
				constituent_id=constituent_id
			)
		except Vote.DoesNotExist:
			Vote.objects.create(
				bill_id=bill_id,
				state=state,
				session=session,
				name=companion_name,
				companion_name=name,
				constituent_id=constituent_id,
				position=request.POST['position']
			)
		else:
			c.position = request.POST['position']
			c.save()

	return HttpResponseRedirect(reverse('bills:detail', args=(state, session, name,)))

bills/templates/bills/detail.html
{% extends 'base.html' %}

<title>{{ bill.name }}</title>

{% block title %}{{ bill.name }}{% if bill.companion_name %}/{{ bill.companion_name }}{% endif %}{% endblock %}

{% block content %}

    <h2>{{ bill.name }}{% if bill.companion_name %}/{{ bill.companion_name }}{% endif %}</h2>
    <p>{{ bill.title }}</p>
    <p>{{ bill.session }}</p>
    <p>{{ bill.subjects }}</p>

    {% if user.is_authenticated %}
        <p><strong>What is your position on this bill?</strong></p>
        <form action="{% url 'bills:vote' bill.state bill.session bill.name %}" method="POST">
        {% csrf_token %}
        <select name="position">
            <option value=""></option>
            <option value="support">Support</option>
            <option value="oppose">Oppose</option>
            <option value="indifferent">Indifferent</option>
        </select>
        <br>
        <br>
        <button type="submit">Vote</button>
        </form>

        <p>{{ position }}</p>
    {% endif %}

    <p>{{ support }} constituent{{ support|pluralize }} support this bill.</p>
    <strong>House Actions on {{ bill.name }}</strong>
    <p>
    {% for a in house_actions %}
        <li>{{ a.action }}</li>
    {% empty %}
        <li>No House actions on {{ bill.name }}</li>
    {% endfor %}
    </p>
    <strong>Senate Actions on {{ bill.name }}</strong>
    <p>
        {% for a in senate_actions %}
            <li>{{ a.action }}</li>
        {% empty %}
            <li>No Senate actions on {{ bill.name }}</li>
        {% endfor %}
    </p>
{% endblock %}

bills/templates/bills/index.html
{% extends 'base.html' %}

<title>{% block title %}Your Bills{% endblock %}</title>

{% block content %}
    <p>
        <strong>Bills You Support</strong>
        {% for s in support %}
            <li><a href="/bills/{{ s.state }}/{{ s.session }}/{{ s.name }}">{{ s.name }}</a>/<a href="/bills/{{ s.state }}/{{ s.session }}/{{ s.name }}">{{ s.companion_name }}</a></li>
        {% empty %}
            <li>You support no bills.</li>
        {% endfor %}
    </p>
    <p>
        <strong>Bills You Oppose</strong>
        {% for o in oppose %}
            <li><a href="/bills/{{ o.state }}/{{ o.session }}/{{ o.name }}">{{ o.name }}</a>/<a href="/bills/{{ o.state }}/{{ o.session }}/{{ o.name }}">{{ o.companion_name }}</a></li>
        {% empty %}
            <li>You oppose no bills.</li>
        {% endfor %}
    </p>
    <p>
        <strong>Bills You May Be Interested In</strong>
        {% for i in interest %}
            <li><a href="/bills/{{ i.state }}/{{ i.session }}/{{ i.name }}">{{ i.name }}</a>/<a href="/bills/{{ i.state }}/{{ i.session }}/{{ i.name }}">{{ i.companion_name }}</a>: {{ i.title }}</li>
        {% empty %}
            <li>As you vote on bills we'll identify new bills you may be interested in.</li>
        {% endfor %}
    </p>
{% endblock %}